services:
  db:
    container_name: notida-db
    image: mysql:latest
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    networks:
      - app-network

  redis:
    container_name: notida-redis
    image: redis:latest
    restart: unless-stopped

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    networks:
      - app-network

  notida:
    container_name: notida

    build:
      context: .
      dockerfile: Dockerfile

    image: seguinleo/notida:latest
    restart: unless-stopped

    env_file:
      - .env

    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}

      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    ports:
      - "8787:80"

    networks:
      - app-network

volumes:
  mysql-data:
  redis-data:

networks:
  app-network:
    driver: bridge
